const TEST = "TEST";
const SESSION= "SESSION";
const ONBOARDING = "ONBOARDING";
const WALLET = "WALLET";
const NOTIFICATION = "NOTIFICATION";
const PRODUCT = "PRODUCT";
const CATEGORIES = "CATEGORIES";
const CART = "CART";
const NAVIGATION = "NAVIGATION";
const WISHLIST = "WISHLIST";

export {
    TEST,
    SESSION,
    ONBOARDING,
    WALLET,
    NOTIFICATION,
    PRODUCT,
    CART,
    NAVIGATION,
    WISHLIST,
    CATEGORIES
};